version: '3'
services:
  postgresql:
    image: postgres:11.5-alpine
    environment:
      POSTGRES_PASSWORD: snello
      POSTGRES_USER: snello
      POSTGRES_DB: snello
    ports:
      - '5432:5432'
  pgadmin4:
    image: dpage/pgadmin4
    ports:
      - '5050:5050'
      - '85:80'
    links:
      - postgresql:postgresql
    depends_on:
      - postgresql
    environment:
      PGADMIN_DEFAULT_EMAIL: info@snello.io
      PGADMIN_DEFAULT_PASSWORD: snello
